# Spring boot project configuration
spring:
  application:
    name: sp-service-smp
  profiles:
    active: production
  main:
    # Disable embed tomcat
    web-environment: true
  messages:
    basename: messages
    cache-seconds: -1
    encoding: utf-8